# Generated by Django 3.2 on 2025-06-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='timestamp',
        ),
    ]
