# Generated by Django 3.2 on 2026-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20260313_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='certificate_min_percentage',
            field=models.FloatField(default=60.0, help_text='Minimum % score required to download certificate'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_answers',
            field=models.JSONField(default=list),
        ),
    ]
