# Generated by Django 3.2 on 2026-03-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_auto_20260313_1907'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_active'], name='video_app_q_is_acti_bcecea_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['start_time'], name='video_app_q_start_t_46937b_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['end_time'], name='video_app_q_end_tim_6cd1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student', 'is_submitted'], name='video_app_q_student_936c35_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'is_submitted'], name='video_app_q_quiz_id_ee05c7_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['started_at'], name='video_app_q_started_4f1579_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['student', 'completed_at'], name='video_app_q_student_41877f_idx'),
        ),
        migrations.AddIndex(
            model_name='quizresult',
            index=models.Index(fields=['quiz', 'completed_at'], name='video_app_q_quiz_id_ee2938_idx'),
        ),
    ]
