# Generated by Django 3.2 on 2025-06-15 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_app', '0004_quizresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videolesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='total_questions',
            field=models.IntegerField(),
        ),
    ]
