# Generated by Django 3.2 on 2025-06-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0006_auto_20250615_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolesson',
            name='folder',
        ),
        migrations.DeleteModel(
            name='VideoFolder',
        ),
    ]
