# Generated by Django 3.2 on 2025-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0008_alter_question_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='credit_point',
            field=models.IntegerField(default=0),
        ),
    ]
