# Generated by Django 3.2 on 2025-06-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0009_auto_20250615_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videolesson',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='mark',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='total_marks',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
