# Generated by Django 3.2 on 2025-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0010_auto_20250615_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='certificate_title',
            field=models.CharField(default='Certificate of Completion', max_length=255),
        ),
    ]
