# Generated by Django 3.2 on 2025-06-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0012_finalcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='certificate_title',
        ),
    ]
