# Generated by Django 3.2 on 2025-06-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0013_auto_20250616_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateconfig',
            name='title',
        ),
        migrations.AddField(
            model_name='certificateconfig',
            name='campaign_name',
            field=models.CharField(default='Your Campaign Name', max_length=255),
        ),
        migrations.AddField(
            model_name='certificateconfig',
            name='institution_name',
            field=models.CharField(default='Your Institution Name', max_length=255),
        ),
    ]
